name: Unit Testing

on:
  workflow_dispatch:

jobs:
  build:
    name: Unit Testing
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Use Python version 3.7
      uses: actions/setup-python@v3
      with:
        python-version: '3.7'
    - name: Setting up environment
      uses: actions/checkout@main
      with:
        environment: azureml:AzureML-sklearn-0.24-ubuntu18.04-py37-cpu@latest
    - name: Specific requirements
      uses: |
        python -m pip install requirements.txt
    - name: Install PyTest
      run: |
        python -m pip install pytest
    - name: Run unit testing
      run: | 
        pytest tests/